//
// Created by Eric Silverman on 13/10/2018.
//

#include <stdio.h>
#include "defs.h"

char *PrSq(const int sq) {

    static char SqStr[3];

    int file = FilesBrd[sq];
    int rank = RanksBrd[sq];

    sprintf(SqStr, "%c%c", ('a'+file), ('1'+rank));

    return SqStr;
}

char *PrMove(const int move) {

    static char MvStr[6];

    int ff = FilesBrd[FROMSQ(move)];
    int rf = RanksBrd[FROMSQ(move)];
    int ft = FilesBrd[TOSQ(move)];
    int rt = RanksBrd[TOSQ(move)];

    int promoted = PROMOTED(move);

    if(promoted) {
        char pchar = 'q';
        if(IsKn(promoted)) {
            pchar = 'n';
        } else if(IsRQ(promoted) && !IsBQ(promoted))  {
            pchar = 'r';
        } else if(!IsRQ(promoted) && IsBQ(promoted))  {
            pchar = 'b';
        }
        sprintf(MvStr, "%c%c%c%c%c", ('a'+ff), ('1'+rf), ('a'+ft), ('1'+rt), pchar);
    } else {
        sprintf(MvStr, "%c%c%c%c", ('a'+ff), ('1'+rf), ('a'+ft), ('1'+rt));
    }

    return MvStr;
}

int ParseMove(char *ptrChar, S_BOARD *pos) {

    ASSERT(CheckBoard(pos));

    if(ptrChar[1] > '8' || ptrChar[1] < '1') return NOMOVE;
    if(ptrChar[3] > '8' || ptrChar[3] < '1') return NOMOVE;
    if(ptrChar[0] > 'h' || ptrChar[0] < 'a') return NOMOVE;
    if(ptrChar[2] > 'h' || ptrChar[2] < 'a') return NOMOVE;

    int from = FR2SQ(ptrChar[0] - 'a', ptrChar[1] - '1');
    int to = FR2SQ(ptrChar[2] - 'a', ptrChar[3] - '1');

    ASSERT(SqOnBoard(from) && SqOnBoard(to));

    S_MOVELIST list[1];
    GenerateAllMoves(pos,list);
    int MoveNum = 0;
    int Move = 0;
    int PromPce = EMPTY;

    for(MoveNum = 0; MoveNum < list->count; ++MoveNum) {
        Move = list->moves[MoveNum].move;
        if(FROMSQ(Move)==from && TOSQ(Move)==to) {
            PromPce = PROMOTED(Move);
            if(PromPce!=EMPTY) {
                if(IsRQ(PromPce) && !IsBQ(PromPce) && ptrChar[4]=='r') {
                    return Move;
                } else if(!IsRQ(PromPce) && IsBQ(PromPce) && ptrChar[4]=='b') {
                    return Move;
                } else if(IsRQ(PromPce) && IsBQ(PromPce) && ptrChar[4]=='q') {
                    return Move;
                } else if(IsKn(PromPce)&& ptrChar[4]=='n') {
                    return Move;
                }
                continue;
            }
            return Move;
        }
    }

    return NOMOVE;
}

void PrintMoveList(const S_MOVELIST *list) {
    int index = 0;
    int score = 0;
    int move = 0;
    printf("MoveList:\n");

    for(index = 0; index < list->count; ++index) {

        move = list->moves[index].move;
        score = list->moves[index].score;

        printf("Move:%d > %s (score:%d)\n",index+1,PrMove(move),score);
    }
    printf("MoveList Total %d Moves:\n\n",list->count);
}

void WriteFenLog(char *fen) {
    FILE *fp;

    fp=fopen(FEN_LOG_FILE, "a");
    if(fp == NULL)
        exit(-1);
    fprintf(fp, "%s\n", fen);
    fclose(fp);
}

void InitTEX() {
    FILE *fp;
    fp=fopen(TEX_GAME_LOG, "a");
    if(fp == NULL)
        exit(-1);
    fprintf(fp, "\\documentclass{article}\n");
    fprintf(fp, "\\usepackage[utf8]{inputenc}\n");
    fprintf(fp, "\\usepackage[english]{babel}\n");
    fprintf(fp, "\\usepackage{skak}\n");
    fprintf(fp, "\\usepackage{geometry}\n");
    fprintf(fp, "\\geometry{textheight = 22.5cm}\n");
    fprintf(fp, "\\begin{document}\n");
    fprintf(fp, "{\\huge Visual game record generated by SpaceDog!}\n\n");
    fprintf(fp, "\\medskip\n\n");
    fprintf(fp, "\\newgame\n\n");
    fclose(fp);
};

void WriteTEX(char *fen) {
    FILE *fp;
    fp=fopen(TEX_GAME_LOG, "a");
    if(fp == NULL)
        exit(-1);
    fprintf(fp, "%s\n\n", fen);
    fprintf(fp, "\\fenboard{%s}\n\n", fen);
    fprintf(fp, "\\showboard\n\n");
    fprintf(fp, "\\bigskip\n\n");
    fclose(fp);
}

void WritePV(const S_BOARD *pos, int depth) {
    int pvMoves, pvNum;
    FILE *fp;
    fp=fopen(TEX_GAME_LOG,"a");
    pvMoves = GetPvLine(depth, pos);
    fprintf(fp, "\\emph{PV:} ");
    for(pvNum=0; pvNum < pvMoves; ++pvNum) {
        fprintf(fp, "%s ", PrMove(pos->PvArray[pvNum]));
    };
    fprintf(fp, "\n\n");
    fclose(fp);
};

void WriteMoveTEX(char *move, int ply) {
    FILE *fp;
    fp=fopen(TEX_GAME_LOG, "a");
    if(fp == NULL)
        exit(-1);
    fprintf(fp, "\\emph{Ply %d:} %s\n\n", ply, move);
    fclose(fp);
};

void EndTEX() {
    FILE *fp;
    fp=fopen(TEX_GAME_LOG, "a");
    if(fp == NULL)
        exit(-1);
    fprintf(fp, "\\end{document}\n");
    fclose(fp);
};